name: Advanced Issue
description: Complex tasks requiring architectural and domain knowledge.
title: "[Advanced]: "
labels: ["advanced"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🧠 Advanced Contributors
        This issue is intended for contributors who are already very familiar with the Terraform-Driven Ray on Kubernetes codebase and its architectural patterns.
        
        **You should feel comfortable:**
        - Navigating multiple modules across terraform and scripts
        - Understanding and modifying core cluster abstractions
        - Reasoning about infrastructure design and backwards compatibility
        - Making changes that may affect public-facing behavior
        
        New developers should start with Good First Issues or Intermediate Issues first.

  - type: textarea
    id: problem-description
    attributes:
      label: 🐞 Problem Description
      description: Describe the problem.
    validations:
      required: true

  - type: textarea
    id: expected-solution
    attributes:
      label: 💡 Proposed / Expected Solution
      description: The proposed solution.
    validations:
      required: true
      
  - type: textarea
    id: implementation-design-notes
    attributes:
      label: 🧠 Implementation & Design Notes
      description: Provide guidance on implementation and design constraints.
    validations:
      required: true

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: To merge this issue, the pull request must
      options:
        - label: Fully address the problem and design goals described above
          required: true
        - label: Maintain backwards compatibility unless explicitly approved otherwise
          required: true
        - label: Follow existing architectural and coding conventions
          required: true
        - label: Pass all CI checks
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📚 Additional Context, Links, or Prior Art
      description: Any other context.
    validations:
      required: false
